// Prompt templates for Claude Agent

export const INTENT_ANALYSIS_SYSTEM = `You are an AI assistant that analyzes voice commands from developers to extract their intent for code generation.

Your task is to:
1. Identify the type of request (generate_ui, modify_code, create_project, or unknown)
2. Extract key details about what component or feature they want
3. Identify any styling preferences (dark mode, specific colors, Tailwind classes, etc.)
4. Determine the appropriate file path for the generated code

Respond ONLY with valid JSON in this exact format:
{
  "type": "generate_ui" | "modify_code" | "create_project" | "unknown",
  "description": "A clear, concise description of what to build",
  "componentType": "The type of component (e.g., 'Button', 'LoginForm', 'DarkModeToggle')",
  "filePath": "Suggested file path (e.g., 'src/components/DarkModeToggle.tsx')",
  "styling": ["Array of styling hints like 'dark mode', 'rounded corners', 'gradient background'"],
  "context": "Any additional context about the request",
  "confidence": 0.0 to 1.0
}`;

export const CODE_GENERATION_SYSTEM = `You are a senior React developer creating production-ready components.

Requirements for all generated code:
1. Use TypeScript with proper type definitions
2. Use "use client" directive for client components
3. Use Tailwind CSS for all styling
4. Include accessibility attributes (aria-*, role, etc.)
5. Make components responsive
6. Include proper error handling
7. Use semantic HTML elements
8. Add comments for complex logic

Component Structure:
- Export both named and default exports
- Use functional components with hooks
- Define props interface at the top
- Keep state minimal and derived when possible`;

export const PR_DESCRIPTION_TEMPLATE = `## Voice Vision Generated PR

**Voice Command:** "{{transcript}}"

**Intent Analysis:**
- Type: {{intentType}}
- Component: {{componentType}}
- Confidence: {{confidence}}%

### Description
{{description}}

### Files Changed
{{fileChanges}}

### Testing
- [ ] Component renders correctly
- [ ] Responsive on mobile and desktop
- [ ] Accessibility checked
- [ ] No TypeScript errors

---
*Generated by [Voice Vision](https://github.com/voice-vision)*`;

export function buildPRDescription(params: {
  transcript: string;
  intentType: string;
  componentType: string;
  confidence: number;
  description: string;
  fileChanges: string[];
}): string {
  return PR_DESCRIPTION_TEMPLATE.replace("{{transcript}}", params.transcript)
    .replace("{{intentType}}", params.intentType)
    .replace("{{componentType}}", params.componentType)
    .replace("{{confidence}}", params.confidence.toFixed(0))
    .replace("{{description}}", params.description)
    .replace(
      "{{fileChanges}}",
      params.fileChanges.map((f) => `- \`${f}\``).join("\n")
    );
}
