import { Octokit } from "@octokit/rest";
import type { GitHubRepoConfig, GitHubFileCommit } from "../types/index.js";

export class GitHubService {
  private octokit: Octokit;
  private username: string | null = null;

  constructor(token: string) {
    this.octokit = new Octokit({ auth: token });
  }

  async getAuthenticatedUser(): Promise<string> {
    if (this.username) return this.username;

    const { data } = await this.octokit.users.getAuthenticated();
    this.username = data.login;
    return this.username;
  }

  async createRepository(
    config: GitHubRepoConfig
  ): Promise<{ owner: string; name: string; url: string }> {
    const { data } = await this.octokit.repos.createForAuthenticatedUser({
      name: config.name,
      description: config.description || "Generated by Voice Vision",
      private: config.private ?? true,
      auto_init: true, // Creates initial commit with README
    });

    return {
      owner: data.owner.login,
      name: data.name,
      url: data.html_url,
    };
  }

  async createBranch(params: {
    owner: string;
    repo: string;
    branch: string;
    fromBranch?: string;
  }): Promise<void> {
    const { owner, repo, branch, fromBranch = "main" } = params;

    // Get the SHA of the source branch
    const { data: refData } = await this.octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${fromBranch}`,
    });

    // Create new branch
    await this.octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branch}`,
      sha: refData.object.sha,
    });
  }

  async pushFiles(params: {
    owner: string;
    repo: string;
    branch: string;
    message: string;
    files: GitHubFileCommit[];
  }): Promise<void> {
    const { owner, repo, branch, message, files } = params;

    // Get the current commit SHA
    const { data: refData } = await this.octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${branch}`,
    });
    const currentCommitSha = refData.object.sha;

    // Get the tree SHA
    const { data: commitData } = await this.octokit.git.getCommit({
      owner,
      repo,
      commit_sha: currentCommitSha,
    });
    const baseTreeSha = commitData.tree.sha;

    // Create blobs for each file
    const blobs = await Promise.all(
      files.map(async (file) => {
        const { data: blobData } = await this.octokit.git.createBlob({
          owner,
          repo,
          content: Buffer.from(file.content).toString("base64"),
          encoding: "base64",
        });
        return {
          path: file.path,
          mode: "100644" as const,
          type: "blob" as const,
          sha: blobData.sha,
        };
      })
    );

    // Create new tree
    const { data: newTree } = await this.octokit.git.createTree({
      owner,
      repo,
      base_tree: baseTreeSha,
      tree: blobs,
    });

    // Create commit
    const { data: newCommit } = await this.octokit.git.createCommit({
      owner,
      repo,
      message,
      tree: newTree.sha,
      parents: [currentCommitSha],
    });

    // Update branch reference
    await this.octokit.git.updateRef({
      owner,
      repo,
      ref: `heads/${branch}`,
      sha: newCommit.sha,
    });
  }

  async createPullRequest(params: {
    owner: string;
    repo: string;
    title: string;
    body?: string;
    head: string;
    base: string;
    draft?: boolean;
  }): Promise<{ url: string; number: number }> {
    const { owner, repo, title, body, head, base, draft = false } = params;

    const { data } = await this.octokit.pulls.create({
      owner,
      repo,
      title,
      body,
      head,
      base,
      draft,
    });

    return {
      url: data.html_url,
      number: data.number,
    };
  }

  async getRepositoryInfo(
    owner: string,
    repo: string
  ): Promise<{
    defaultBranch: string;
    url: string;
  }> {
    const { data } = await this.octokit.repos.get({ owner, repo });
    return {
      defaultBranch: data.default_branch,
      url: data.html_url,
    };
  }

  async getRepositoryContents(
    owner: string,
    repo: string,
    path: string = ""
  ): Promise<string> {
    const contents: string[] = [];
    const maxFiles = 40; // Increased limit for better context
    let fileCount = 0;

    // Priority directories to scan first (most likely to contain important code)
    const priorityDirs = ["src", "app", "components", "lib", "pages", "hooks", "utils", "services"];
    const skipDirs = new Set([
      "node_modules", ".git", "dist", "build", ".next", "coverage",
      ".cache", ".turbo", "out", "__pycache__", ".venv", "venv",
      "vendor", "target", "bin", "obj", ".idea", ".vscode"
    ]);

    const codeExtensions = new Set([
      "ts", "tsx", "js", "jsx", "py", "go", "rs", "java", "kt",
      "json", "yaml", "yml", "css", "scss", "less", "html", "vue", "svelte"
    ]);

    // Files to always include if they exist
    const importantFiles = new Set([
      "package.json", "tsconfig.json", "next.config.js", "next.config.ts",
      "vite.config.ts", "tailwind.config.js", "tailwind.config.ts"
    ]);

    const fetchContents = async (currentPath: string, priority: number = 0): Promise<void> => {
      if (fileCount >= maxFiles) return;

      try {
        const { data } = await this.octokit.repos.getContent({
          owner,
          repo,
          path: currentPath,
        });

        if (Array.isArray(data)) {
          // Sort: prioritize directories and important files
          const sorted = data.sort((a, b) => {
            const aIsPriority = priorityDirs.includes(a.name) ? 1 : 0;
            const bIsPriority = priorityDirs.includes(b.name) ? 1 : 0;
            const aIsImportant = importantFiles.has(a.name) ? 1 : 0;
            const bIsImportant = importantFiles.has(b.name) ? 1 : 0;
            return (bIsPriority + bIsImportant) - (aIsPriority + aIsImportant);
          });

          for (const item of sorted) {
            if (fileCount >= maxFiles) break;

            // Skip non-essential directories
            if (skipDirs.has(item.name) || item.name.startsWith(".")) {
              continue;
            }

            if (item.type === "dir") {
              // Prioritize scanning important directories
              const dirPriority = priorityDirs.includes(item.name) ? priority : priority + 1;
              if (dirPriority <= 2) { // Only go 2 levels deep for non-priority dirs
                await fetchContents(item.path, dirPriority);
              }
            } else if (item.type === "file") {
              const ext = item.name.split(".").pop()?.toLowerCase();
              const isCodeFile = ext && codeExtensions.has(ext);
              const isImportant = importantFiles.has(item.name);

              if ((isCodeFile || isImportant) && item.size < 50000) {
                try {
                  const { data: fileData } = await this.octokit.repos.getContent({
                    owner,
                    repo,
                    path: item.path,
                  });

                  if (!Array.isArray(fileData) && fileData.type === "file") {
                    const content = Buffer.from(
                      fileData.content,
                      "base64"
                    ).toString("utf-8");
                    contents.push(`\n--- ${item.path} ---\n${content}`);
                    fileCount++;
                  }
                } catch {
                  // Skip files that can't be read
                }
              }
            }
          }
        }
      } catch {
        // Directory doesn't exist or can't be read
      }
    };

    await fetchContents(path);

    // Add a summary at the top
    const summary = `Repository: ${owner}/${repo}\nFiles analyzed: ${fileCount}\n`;
    return summary + contents.join("\n");
  }
}
