import { GitHubService } from "./github.js";
import { V0Service, generateFallbackCode } from "./v0.js";
import { ClaudeAgent } from "./claude-agent.js";
import type {
  GeneratedCode,
  PRResult,
  GitHubRepoConfig,
  GitHubFileCommit,
  Intent,
} from "../types/index.js";

interface OrchestratorConfig {
  githubToken: string;
  v0ApiKey: string;
  vercelToken?: string;
  anthropicApiKey?: string;
}

interface GenerateCodeParams {
  prompt: string;
  componentType?: string;
  styling?: string[];
  context?: string;
}

export class MCPOrchestrator {
  private github: GitHubService;
  private v0: V0Service;
  private claude: ClaudeAgent | null;

  constructor(config: OrchestratorConfig) {
    this.github = new GitHubService(config.githubToken);
    this.v0 = new V0Service(config.v0ApiKey);
    this.claude = config.anthropicApiKey
      ? new ClaudeAgent(config.anthropicApiKey)
      : null;
  }

  async generateCode(params: GenerateCodeParams): Promise<GeneratedCode> {
    const { prompt, componentType = "Component", styling = [] } = params;

    try {
      // Try v0 API first
      const response = await this.v0.generateUI({
        prompt: this.buildV0Prompt(prompt, componentType, styling),
        model: "v0-1.5-md",
      });

      // Extract component name for file path
      const componentName = this.extractComponentName(componentType, prompt);
      const filePath = `src/components/${componentName}.tsx`;

      return {
        code: response.code,
        language: "typescript",
        filePath,
        explanation: `Generated ${componentName} component based on: "${prompt}"`,
      };
    } catch (error) {
      console.warn("v0 API failed, using fallback:", error);

      // Fallback to basic template
      const componentName = this.extractComponentName(componentType, prompt);
      const code = generateFallbackCode(componentName, prompt, styling);

      return {
        code,
        language: "typescript",
        filePath: `src/components/${componentName}.tsx`,
        explanation: `Generated ${componentName} component (fallback) based on: "${prompt}"`,
      };
    }
  }

  async createRepository(
    config: GitHubRepoConfig
  ): Promise<{ owner: string; name: string; url: string }> {
    return this.github.createRepository(config);
  }

  async createBranch(params: {
    owner: string;
    repo: string;
    branch: string;
    fromBranch?: string;
  }): Promise<void> {
    return this.github.createBranch(params);
  }

  async pushFiles(params: {
    owner: string;
    repo: string;
    branch: string;
    message: string;
    files: GitHubFileCommit[];
  }): Promise<void> {
    return this.github.pushFiles(params);
  }

  async createPullRequest(params: {
    owner: string;
    repo: string;
    title: string;
    body?: string;
    head: string;
    base: string;
    draft?: boolean;
  }): Promise<PRResult> {
    const result = await this.github.createPullRequest(params);
    const repoInfo = await this.github.getRepositoryInfo(
      params.owner,
      params.repo
    );

    return {
      url: result.url,
      number: result.number,
      title: params.title,
      repoUrl: repoInfo.url,
      // Preview URL would come from Vercel deployment
      previewUrl: undefined,
    };
  }

  // Execute full pipeline from intent to PR
  async executePipeline(
    intent: Intent,
    transcript: string
  ): Promise<{
    code: GeneratedCode;
    pr: PRResult;
  }> {
    // Generate code
    const code = await this.generateCode({
      prompt: intent.description,
      componentType: intent.componentType,
      styling: intent.styling,
      context: intent.context,
    });

    // Create repository
    const repoName = `voice-vision-${Date.now()}`;
    const repo = await this.createRepository({
      name: repoName,
      description: `Generated by Voice Vision: ${intent.description}`,
      private: true,
    });

    // Push initial code to main
    await this.pushFiles({
      owner: repo.owner,
      repo: repo.name,
      branch: "main",
      message: "feat: initial generated code from Voice Vision",
      files: [
        { path: code.filePath, content: code.code },
        {
          path: "package.json",
          content: JSON.stringify(
            {
              name: repoName,
              version: "1.0.0",
              dependencies: {
                react: "^19.0.0",
                "react-dom": "^19.0.0",
                tailwindcss: "^3.4.0",
              },
            },
            null,
            2
          ),
        },
      ],
    });

    // Create feature branch
    const branchName = "feature/voice-generated";
    await this.createBranch({
      owner: repo.owner,
      repo: repo.name,
      branch: branchName,
      fromBranch: "main",
    });

    // Create PR
    const pr = await this.createPullRequest({
      owner: repo.owner,
      repo: repo.name,
      title: `feat: ${intent.description}`,
      body: this.buildPRBody(intent, transcript, code),
      head: branchName,
      base: "main",
    });

    return { code, pr };
  }

  private buildV0Prompt(
    description: string,
    componentType: string,
    styling: string[]
  ): string {
    let prompt = `Create a React component with TypeScript and Tailwind CSS.

Component: ${componentType}
Description: ${description}

Requirements:
- Use "use client" directive for client components
- Use functional components with hooks
- Include proper TypeScript types
- Use Tailwind CSS for all styling
- Make it responsive and accessible
- Include hover and focus states`;

    if (styling.length > 0) {
      prompt += `\n\nStyling preferences:\n${styling.map((s) => `- ${s}`).join("\n")}`;
    }

    return prompt;
  }

  private extractComponentName(componentType: string, prompt: string): string {
    // Clean up component type or extract from prompt
    if (componentType && componentType !== "Not specified") {
      return componentType.replace(/\s+/g, "");
    }

    // Extract from prompt - look for common patterns
    const patterns = [
      /create\s+(?:a\s+)?(\w+)/i,
      /add\s+(?:a\s+)?(\w+)/i,
      /build\s+(?:a\s+)?(\w+)/i,
      /(\w+)\s+component/i,
      /(\w+)\s+button/i,
      /(\w+)\s+form/i,
    ];

    for (const pattern of patterns) {
      const match = prompt.match(pattern);
      if (match) {
        return this.toPascalCase(match[1]);
      }
    }

    return "GeneratedComponent";
  }

  private toPascalCase(str: string): string {
    return str
      .split(/[-_\s]+/)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join("");
  }

  async getRepositoryContents(owner: string, repo: string): Promise<string> {
    return this.github.getRepositoryContents(owner, repo);
  }

  getClaudeAgent(): ClaudeAgent | null {
    return this.claude;
  }

  private buildPRBody(
    intent: Intent,
    transcript: string,
    code: GeneratedCode
  ): string {
    return `## Voice Vision Generated PR

**Voice Command:** "${transcript}"

**Intent Analysis:**
- Type: ${intent.type}
- Component: ${intent.componentType || "UI Component"}
- Confidence: ${(intent.confidence * 100).toFixed(0)}%

### Description
${intent.description}

### Files Changed
- \`${code.filePath}\`

${code.explanation ? `### Notes\n${code.explanation}` : ""}

---
*Generated by [Voice Vision](https://github.com/voice-vision) - Voice-to-PR Developer Tool*`;
  }
}
